sudo: required
services:
 - docker

before_install:
 - docker build -t akash/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true akash/docker-react npm run test --coverage

deploy:
 provider: elasticbeanstalk
 edge: true
 region: "ap-south-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-ap-south-1-548138670591"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: "$AWS_AK"
 secret_access_key: "$AWS_SK"
 skip_cleanup: true
